#!/bin/sh

if [ -f ./pid ]; then
    OLDPID=`cat ./pid`
    OLDPNAME=`ps -p $OLDPID -o command=`
    if [ "$OLDPNAME" = "node \"${BASH_SOURCE%/*}/etcports.js\"" ]; then
        kill -9 $OLDPID
        echo "Stopped running etcports:$OLDPID"
    fi
    rm ./pid
fi

if [ "$1" = "--stop" ] ; then
    exit 1
fi

node "${BASH_SOURCE%/*}/etcports.js" &
PID=$!
echo "Started etcports with PID:$PID"
echo $PID > ./pid
